[package]
name = "idols_launcher"
version = "1.0.11"
description = "idols launcher"
authors = ["hqnatx"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri-plugin-deep-link = { git = "https://github.com/FabianLars/tauri-plugin-deep-link", branch = "main" }
reqwest = { version = "0.11.3", features = ["stream"] }
tauri = { version = "1.5", features = [ "api-all"] }
serde = { version = "1.0", features = ["derive"] }
window-shadows = "0.2.2"
window-vibrancy = "0.4"
futures-util = "0.3.14"
tasklist = "0.2.13"
serde_json = "1.0"
tokio = "1.28.2"
sha2 = "0.10.8"

[features]
custom-protocol = ["tauri/custom-protocol"]
